### ISSUE TITLE
Encoding Details

### ISSUE THREAD

**Issue by ggnull35** [bbc/turingcodec#15]
Hi,

Does Turing Codec supports YUV 4:2:2 10bit encoding?
Is there any info on encoding capabilities?

Kind Regards,

**Comment by matteonaccari** [comment]
Hello there and thanks for your interest in the Turing codec project!

The codec supports 10 bit encoding of planar YUV format in 4:2:0 chroma format. Chrominance resolutions such as 4:2:2 and 4:4:4 require Version 2 profiles of HEVC (collectively known as RExt) which at the moment are not support in the codec.
