### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by ghost** [bbc/turingcodec#6]
<SNIP>

Header has information about licensing

**Comment by kupix** [comment]
Thanks for comment Kurosu - attribution and licensing is of course very important. Would you mind describing the changes you believe are needed for attribution/copyright to be correct? I don't want to try to improve this and for it still to be unclear.

**Comment by ghost** [comment]
I have edited my initial comment, as I didn't read the bottom of the license header. There is attribution/copyright there, but I am not a lawyer, so I can't comment on its validity.

In any case, I'm not the author of either code, so I'm not making any claim here of what's appropriate.

**Comment by matteonaccari** [comment]
The Turing codec is licensed under GPLv2 and a commercial license is also available for those who are interested.
