### ISSUE TITLE
cna NOT compiled in linux

### ISSUE THREAD

**Issue by annci62** [bbc/turingcodec#7]
Hello@matteonaccari,  
I have download these codec, but they can NOT compiled. Error is reported:
 turingcodec/havoc/pred_inter.h:35: error：expected unqualified-id before ‘using’

g++ version:4.4.7
 contos 6.5
 Could you tell me how to resolve this problem?Thank you very much

**Comment by matteonaccari** [comment]
Hi Annci62,

Turing is written using the C++11 language which is supported from g++ Version 4.8 and above. I suggest you to try with an up-to-date version of the compiler.
Best regards,
Matteo Naccari

**Comment by annci62** [comment]
HI, Metteonaccari,

I will try it, thank you ver much!

Best Wishes,
annci

**Comment by matteonaccari** [comment]
Hello Annci62,

I assume you are now able to build the Turing codec with an up-to-date version of g++. I'm closing this issue but feel free to reopen should you have any additional problems.

**Comment by annci62** [comment]
Hello matteonaccari,
 I am able to build the codec, thank you very much

**Comment by matteonaccari** [comment]
Brilliant, I'm glad to hear that. If you need any further assistance with the codec usage, do not hesitate to contact us.
