### ISSUE TITLE
Please clarify patent status

### ISSUE THREAD

**Issue by ausil** [bbc/turingcodec#9]
I assume there is some patents involved, is there is patent grant?  a clear statement over patents, usages and distribution rights is needed.

**Comment by matteonaccari** [comment]
The distribution rights of the code are regulated by the GPLv2 license attached to the Turing codec. For any issue related to pending IPRs and potential commercial license, please contact info@turingcodec.org.

**Comment by ausil** [comment]
That was not the question. is there patents and if so what usage rights are there?  I would like to put the codec in a linux distro. But if there are patents preventing all people from using the codec then we can not do so.

**Comment by matteonaccari** [comment]
Hi Dennis,
It's great that you're thinking about integrating the codec into a Linux distro. However, the answer to your question is not a simple, straight, yes or no, it depends on the use you want to make for this Linux distro and how to want to deal with the MPEG-LA terms for HEVC (which are separated by any potential IPR we have in this codec). So can I insist to take this conversation on info@turingcodec.org? Thanks
